### ISSUE TITLE
Uncaught TypeError: fightData.friendlyPets[petIDs.indexOf(...)] is undefined

### ISSUE THREAD

**Issue by bgrabow** [Maarslet/DebuffCheck#2]
The debuffs knocked off tool appears to be broken. The example I'm looking at is:

https://maarslet.github.io/DebuffCheck/

Log ID: gpD4zQj1WrCVFYAd

Error: 

> Uncaught TypeError: fightData.friendlyPets[petIDs.indexOf(...)] is undefined
    classColor https://maarslet.github.io/DebuffCheck/debuffAnalyser.js:305
    processInput https://maarslet.github.io/DebuffCheck/debuffAnalyser.js:223
    startCode https://maarslet.github.io/DebuffCheck/:13
debuffAnalyser.js:305:86
    classColor https://maarslet.github.io/DebuffCheck/debuffAnalyser.js:305
    processInput https://maarslet.github.io/DebuffCheck/debuffAnalyser.js:223
    startCode https://maarslet.github.io/DebuffCheck/:13

In the UI I get the message `Code stopped for some reason` and the display of debuffs pushed off does not appear.

**Comment by Maarslet** [comment]
Looks like Faerlina has a weird debuff, put up a quick fix for now
