### ISSUE TITLE
Logs from multiple days not parsed

### ISSUE THREAD

**Issue by yamyamyamyamyam** [Maarslet/DebuffCheck#3]
Hi, I love this tool! Wanted to bring up a small issue where in a log like this one ( https://classic.warcraftlogs.com/reports/g4GdCQyfY32Bz1NP ), which spans over multiple days, the main content of the log won't be parsed by the tool because of the built-in 100000000 limit for length. I assume the 100000000 limit is there as a sanity check so it doesn't try to parse a ridiculously long log. I made a fork where I increased the limit to 900000000 as a cludge, but maybe you have a better solution.

Thanks again, this tool is very useful!

**Comment by Maarslet** [comment]
End limit increased by a factor of ten
